function [infa, infb] = refpaninf(del,X,Yin)
% REFPANINF Compute influence coefficients for a vortex-sheet panel on the x-axis.

% Deal with panel boundary numerical issues
Y = Yin;
Y(abs(Y)<1e-6) = 1e-6;

% Calculation of coefficients
I0 = - 1/(4*pi) * (X .* log(X.^2 + Y.^2) ...
                - (X - del) .* log((X - del).^2 + Y.^2) ...
                - 2 .* del ...
                + 2 * Y .* (atan(X ./ Y)- atan((X - del) ./ Y)) ...
                );

I1 = 1/(8*pi) * ((X.^2 + Y.^2) .* log(X.^2 + Y.^2) ...
              - ((X - del).^2 + Y.^2) .* log((X - del).^2 + Y.^2) ...
              - 2 * X .* del ...
              + del.^2 ...
              );

infa = (1 - X / del) .* I0 - I1 / del;
infb = (X / del) .* I0 + I1 / del;

end